### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by bmj524** [GuillaumeMougeot/DogFaceNet#2]
I ran command python ./dogfacenet/dogfacenet.py with environment ubuntu 18.04.2 LTS, python 3.6.8, and tensorflow 1.13.1.

And I got this error. I don't have any idea to fix this error and why this error show up.

Traceback (most recent call last):
  File "./dogfacenet/dogfacenet.py", line 219, in <module>
    validation_steps=VALIDATION_STEPS)]
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 177, in model_iteration
    batch_data = _get_next_batch(output_generator, mode)
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 258, in _get_next_batch
    generator_output = next(output_generator)
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 767, in get
    six.reraise(*sys.exc_info())
  File "/home/aji3rang/.local/lib/python3.6/site-packages/six.py", line 696, in reraise
    raise value
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 743, in get
    inputs = self.queue.get(block=True).get()
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/utils/data_utils.py", line 680, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "/home/aji3rang/dognet/DogFaceNet/dogfacenet/online_training.py", line 329, in online_adaptive_hard_image_generator
    steps=int(np.ceil(len(subfilenames)/32)))
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1536, in predict_generator
    verbose=verbose)
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_generator.py", line 171, in model_iteration
    model.reset_metrics()
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 1119, in reset_metrics
    m.reset_states()
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/metrics.py", line 460, in reset_states
    K.set_value(v, 0)
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 2847, in set_value
    get_session().run(assign_op, feed_dict={assign_placeholder: value})
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/aji3rang/anaconda3/envs/tf3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1077, in _run
    raise RuntimeError('The Session graph is empty.  Add operations to the '
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

**Comment by leiluoray1** [comment]
use tensorflow == 1.12.0.
